VIA_ENABLE      = no
LTO_ENABLE      = yes

MOUSEKEY_ENABLE = yes
OS_DETECTION_ENABLE = yes
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
